#' addMetadataToFlowSOM
#'
#' @param fsom A FlowSOM object as generated by the FlowSOM function.
#' @param aggregate The aggregate file used to create the given FlowSOM object.
#'
#' @return A FlowSOM object with added metadata.
#'
#' @export
addMetadataToFlowSOM = function(fsom, aggregate) {
  if (!inherits(fsom, "FlowSOM")) {
    stop("fsom must be a FlowSOM object.")
  }

  fsom$metadata <- list(
    aggregate_file <- aggregate@description$FILENAME
    # preprocessed_files_dir <- dir_prepr
  )

  return(fsom)
}

#' filterFCS
#'
#' @param ff A flowFrame.
#' @param clusters A character vector specifying which clusters to keep. Default
#' is \code{NULL}.
#' @param metaclusters A character vector specifying which metaclusters to keep.
#' Default is \code{NULL}.
#'
#' @return A flowFrame, where only cells belonging to the given clusters or
#' metaclusters are included.
#'
#' @export
filterFCS = function(ff, clusters = NULL, metaclusters = NULL) {
  filter_clust = flowCore::exprs(ff)[,"FlowSOM_cluster"] %in% clusters
  filter_meta = flowCore::exprs(ff)[,"FlowSOM_meta"] %in% metaclusters
  filter = which(filter_clust | filter_meta)

  filtered = ff[filter]
  return(filtered)
}

#' createFilteredAggregate
#'
#' Filter preprocessed .fcs files to create a new aggregate file
#'
#' @param fsom A FlowSOM object as generated by the FlowSOM function.
#' @param num_cells The total number of cells to include in the aggregate file.
#' @param clusters A numeric vector listing the clusters of interest.
#' @param metaclusters A character vector listing the metaclusters of interest.
#' @param agg_name An .fcs filename. Default is "filtered_aggregate.fcs".
#' @param dir_save If a directory path is given, then the filtered .fcs
#' files used to create the aggregate file will be saved there. If \code{NULL}
#' (default), then they will be discarded.
#'
#' @details
#' It is only necessary to define one of the arguments \code{clusters} and
#' \code{metaclusters}, but the user may use both if they wish.
#'
#' This function takes in a group of clustered .fcs files, as generated
#' by \code{FlowSOM::SaveClustersToFCS}, and subsets them to create a new set of
#' .fcs files that contain only the cells included in the given metaclusters
#' and/or clusters. If desired, these new .fcs files are then written to a new
#' directory, whose name is specified by the user with the \code{dir_save}
#' parameter. Note that it is only necessary to save the files if you intend to perform
#' additional reclustering on them, otherwise they may be safely deleted. The
#' aggregate file is written to the directory saved in \code{dir_agg()} under the
#' name specified by \code{agg_name}.
#'
#' @return An aggregated flowFrame, where only cells belonging to the given
#' metaclusters and/or clusters are included.
#'
#' @export
createFilteredAggregate = function(fsom, num_cells, clusters = NULL,
                                   metaclusters = NULL,
                                   agg_name = "filtered_aggregate.fcs",
                                   dir_save = NULL) {
  print(paste0("Creating aggregate with files from directory ", dir_clustr(), "..."))

  metaclusters = which(levels(fsom$metaclustering) == metaclusters)

  frames = lapply(list.files(dir_clustr(), full.names = TRUE), flowCore::read.FCS)

  filtered_frames = lapply(frames, filterFCS, clusters, metaclusters)

  if (!is.null(dir_save) && !dir.exists(dir_save)) {
    dir.create(dir_save)

    names(filtered_frames) = paste0(dir_save, list.files(dir_prepr()))

    for (i in 1:length(filtered_frames)) {
      flowCore::write.FCS(x = methods::as(filtered_frames[[i]], "flowFrame"),
                          filename = names(filtered_frames)[i])
    }
  }

  filtered_fs = methods::as(filtered_frames, "flowSet")

  agg = FlowSOM::AggregateFlowFrames(filtered_fs,
                                     cTotal = num_cells,
                                     writeOutput = TRUE,
                                     outputFile = paste0(dir_agg(), agg_name))
  return(agg)
}
