#' plotTSNE
#'
#' Plot a t-SNE dimension reduction of FlowSOM data, colored by metacluster.
#'
#' @param fsom The FlowSOM object whose data you would like to plot.
#' @param num_cells The total number of cells you would like to use for the
#' dimension reduction.
#' @param point_size Optional parameter to adjust the size of the plotted points.
#' Default is 1.5.
#' @param seed Optional parameter to set a seed for reproducibility.
#'
#' @return A t-SNE plot made with ggplot2.
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#'
#' plotTSNE(fsom, num_cells = 5000)
#'
#' plotTSNE(fsom, num_cells = 5000, point_size = 3, seed = 42)
plotTSNE = function(fsom, num_cells, point_size = 1.5, seed = NULL) {
  if (!is.null(seed)) set.seed(seed)

  tsne = FlowSOM::PlotDimRed(fsom = fsom,
                             colorBy = "metaclusters",
                             colors = viridisLite::viridis(length(levels(fsom$metaclustering)), option = "turbo"),
                             cTotal = num_cells,
                             dimred = Rtsne::Rtsne)

  tsne$layers[[1]]$geom_params$pointsize = point_size
  tsne$layers[[2]]$geom_params$max.overlaps = 50

  return(tsne)
}

#' plotUMAPOld
#'
#' Plot a UMAP dimension reduction of FlowSOM data, colored by metacluster.
#'
#' @param fsom The FlowSOM object whose data you would like to plot.
#' @param num_cells The total number of cells you would like to use for the
#' dimension reduction.
#' @param point_size Optional parameter to adjust the size of the plotted points.
#' Default is 1.5.
#' @param seed Optional parameter to set a seed for reproducibility.
#'
#' @return A UMAP plot made with ggplot2.
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#'
#' plotUMAPOld(fsom, num_cells = 5000)
#'
#' plotUMAPOld(fsom, num_cells = 5000, point_size = 3, seed = 42)
plotUMAPOld = function(fsom, num_cells, point_size = 1.5, seed = NULL) {
  if (!is.null(seed)) set.seed(seed)

  umap = FlowSOM::PlotDimRed(fsom = fsom,
                             colorBy = "metaclusters",
                             colors = viridisLite::viridis(length(levels(fsom$metaclustering)), option = "turbo"),
                             cTotal = num_cells,
                             dimred = umap::umap,
                             extractLayout = function(dimred) {
                               dimred$layout
                               })

  umap$layers[[1]]$geom_params$pointsize = point_size
  umap$layers[[2]]$geom_params$max.overlaps = 50

  return(umap)
}

#' plotMetaclusterMFIs
#'
#' Plot a heatmap of metacluster MFIs.
#'
#' @param fsom A FlowSOM object as generated by the FlowSOM function.
#' @param markers_of_interest A character vector specifying which markers you
#' would like to include in the plot. Default is fsom$map$colsUsed (the markers
#' used for clustering).
#' @param ... Additional parameters to pass to \code{ComplexHeatmap::Heatmap}.
#'
#' @return A heatmap of MFIs made with ComplexHeatmap, where each column is a
#' marker of interest, and each row is a metacluster.
#'
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#' plotMetaclusterMFIs(fsom)
plotMetaclusterMFIs = function(fsom, markers_of_interest = fsom$map$colsUsed, ...) {

  mfi_mat = FlowSOM::GetMetaclusterMFIs(fsom = fsom, colsUsed = FALSE, prettyColnames = FALSE)
  mfi_mat = mfi_mat[, which(colnames(mfi_mat) %in% FlowSOM::GetChannels(fsom, markers_of_interest))]
  colnames(mfi_mat) = fsom$prettyColnames[colnames(mfi_mat)]
  rownames(mfi_mat) = levels(FlowSOM::GetMetaclusters(fsom))

  default_options = list(border = TRUE,
                         show_row_names = TRUE,
                         heatmap_legend_param = list(
                           title = "Expression",
                           title_gp = grid::gpar(fontsize = 9),
                           labels_gp = grid::gpar(fontsize = 8)))

  additional_options = list(...)

  heatmap_options = utils::modifyList(default_options, additional_options)

  mfi_heatmap = do.call(ComplexHeatmap::Heatmap, c(list(matrix = as.matrix(mfi_mat)), heatmap_options))

  return(mfi_heatmap)
}

#' plotClusterMFIs
#'
#' Plot a heatmap of cluster MFIs.
#'
#' @param fsom The FlowSOM object whose data you would like to plot.
#' @param markers_of_interest A character vector specifying which markers you
#' would like to include in the plot. Default is fsom$map$colsUsed (the markers
#' used for clustering).
#' @param metaclusters A vector specifying which metaclusters whose clusters
#' you would like to include in the plot. If NULL (default), all clusters are included.
#' @param ... Additional parameters to pass to \code{ComplexHeatmap::Heatmap}.
#'
#' @return A heatmap of MFIs made with ComplexHeatmap, where each column is a
#' marker of interest, and each row is a cluster.
#'
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#'
#' # Plot all clusters
#' plotClusterMFIs(fsom)
#'
#' # Plot only clusters belonging to metaclusters 9 and 12
#' plotClusterMFIs(fsom, metaclusters = c(9, 12))
plotClusterMFIs = function(fsom, markers_of_interest = fsom$map$colsUsed,
                           metaclusters = NULL, ...) {

  mfi_mat = FlowSOM::GetClusterMFIs(fsom, colsUsed = FALSE, prettyColnames = FALSE)
  mfi_mat = mfi_mat[, which(colnames(mfi_mat) %in% FlowSOM::GetChannels(fsom, markers_of_interest))]

  if (!is.null(metaclusters)) {
    ind = fsom$metaclustering %in% metaclusters
    if (!(TRUE %in% ind)) {
      stop("No clusters exist in the given metacluster(s).")
    }
    mfi_mat = mfi_mat[ind, ]
  }

  colnames(mfi_mat) = fsom$prettyColnames[colnames(mfi_mat)]

  default_options = list(border = TRUE,
                         show_row_names = TRUE,
                         show_column_dend = FALSE,
                         row_names_gp = grid::gpar(fontsize = 4),
                         column_names_gp = grid::gpar(fontsize = 6),
                         width = grid::unit(0.5, "npc"),
                         heatmap_legend_param = list(
                           title = "Expression",
                           title_gp = grid::gpar(fontsize = 9),
                           labels_gp = grid::gpar(fontsize = 8)))

  additional_options = list(...)

  heatmap_options = utils::modifyList(default_options, additional_options)

  mfi_heatmap = do.call(ComplexHeatmap::Heatmap, c(list(matrix = as.matrix(mfi_mat)), heatmap_options))

  return(mfi_heatmap)
}

#' searchByExpression
#'
#' Search MST for nodes with certain marker expressions.
#'
#' @param fsom A FlowSOM object as generated by the FlowSOM function.
#' @param levels A list specifying channels of interest and whether they are
#' high or low. Note that searching for intermediate expression is not supported.
#' See examples for the proper format of this variable.
#'
#' @return An MST plot, where nodes with the given expression levels are
#' highlighted and labeled as "True".
#'
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#'
#' searchByExpression(fsom,
#'                    levels = c("BUV661-A" = "high",
#'                               "APC-Cy7-A" = "low"))
#'
#' searchByExpression(fsom,
#'                    levels = c("BUV805-A" = "low",
#'                               "APC-Cy7-A" = "high",
#'                               "Alexa Fluor 700-A" = "high"))
searchByExpression = function(fsom, levels) {
  query = levels
  query_res = FlowSOM::QueryStarPlot(fsom, query, equalNodeSize = TRUE, plot = FALSE)
  cell_types = factor(rep("False", fsom$map$nNodes),
                      levels = c("False", "True"))
  cell_types[query_res$selected] = "True"
  FlowSOM::PlotStars(fsom, backgroundValues = cell_types)
}

#' plotLabeled2DScatter
#'
#' Plot 2D scatterplot of FlowSOM clusters, with (meta)cluster number labels for
#' each cluster center.
#'
#' @param fsom A FlowSOM object as generated by the FlowSOM function.
#' @param channelpair A vector specifying which two channels to plot.
#' @param clusters A vector of cluster indices.
#' @param metaclusters A vector of metacluster indices.
#' @param label_type A string specifying whether you would like the cluster
#' centers to be labeled with the cluster or metacluster they belong to, either
#' "cluster" or "metacluster".
#'
#'
#' @return A scatterplot made with ggplot and \code{FlowSOM::Plot2DScatters}.
#'
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#'
#' plotLabeled2DScatter(fsom,
#'                      c("APC-Cy7-A", "BUV563-A"),
#'                      metaclusters = c(3, 7, 10),
#'                      label_type = "cluster")
plotLabeled2DScatter = function(fsom, channelpair, clusters = NULL, metaclusters = NULL,
                                label_type = c("cluster", "metacluster")) {

  if (is.null(clusters) && is.null(metaclusters)) {
    stop("clusters and/or metaclusters must be a vector of indices.")

  } else if (is.null(clusters) && !is.null(metaclusters)) {
    all_clust = which(fsom$metaclustering %in% metaclusters)

  } else if (!is.null(clusters) && is.null(metaclusters)) {
    all_clust = clusters

  } else if (!is.null(clusters) && !is.null(metaclusters)) {
    meta_nodes = which(fsom$metaclustering %in% metaclusters)
    all_clust = unique(c(meta_nodes, clusters))

  }

  if (length(all_clust) == 1) {
    mfis = matrix(FlowSOM::GetClusterMFIs(fsom)[all_clust, channelpair],
                  nrow = 1,
                  dimnames = list(all_clust, channelpair))
  } else {
    mfis = FlowSOM::GetClusterMFIs(fsom)[all_clust, channelpair]
  }

  df = as.data.frame(mfis)

  switch(label_type,
         cluster = {labs <- rownames(df)},
         metacluster = {labs <- fsom$metaclustering[all_clust]},
         stop("label_type must be either 'cluster' or 'metacluster'")
  )

  p = FlowSOM::Plot2DScatters(fsom = fsom,
                              channelpairs = list(channelpair),
                              clusters = clusters,
                              metaclusters = metaclusters,
                              plotFile = NULL,
                              density = FALSE,
                              centers = FALSE)

  for (i in 1:length(p)) {
    p[[i]] = p[[i]] + ggplot2::geom_label(data = df,
                                          ggplot2::aes(x = df[,1], y = df[,2], label = labs),
                                          color = "black", size = 2.5, fontface = "bold")
  }

  return(p)
}

#' plotUMAP
#'
#' Plots UMAP colored by metacluster.
#'
#' @param fsom A FlowSOM object as generated by the FlowSOM function.
#' @param num_cells The number of cells to use for the dimension reduction.
#' Default is 5000.
#'
#' @return
#' A UMAP plot drawn with ggplot2.
#'
#' @export
#'
#' @examples
#' file <- system.file("extdata", "sample_aggregate.fcs", package = "flowFun")
#' fsom <- FlowSOM::FlowSOM(file,
#'                          colsToUse = c(10, 12:14, 16, 18:23, 25:32, 34),
#'                          nClus = 15,
#'                          seed = 42)
#'
#' plotUMAP(fsom)
#'
#' plotUMAP(fsom, num_cells = 10000)
plotUMAP = function(fsom, num_cells = 5000) {

  set.seed(42)
  inds = sample(nrow(fsom$data), num_cells)

  dat = fsom$data[inds, fsom$map$colsUsed]

  umap = umap::umap(dat)

  meta_vec = FlowSOM::GetMetaclusters(fsom)[inds]

  # add parameter for choosing order of legend

  umap_df = data.frame(umap$layout, Metacluster = meta_vec, Indices = inds)

  p = ggplot2::ggplot(umap_df) +
    scattermore::geom_scattermore(ggplot2::aes(x = umap_df$X1, y = umap_df$X2,
                                               color = umap_df$Metacluster),
                                  pointsize = 2) +
    ggplot2::theme_void()

  return(p)
}
